---
title: "data summaries"
author: "Kaito Ibaraki"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#loads all sheets into dataframes

```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(docxtractr)
library(lubridate)
library(tidyr)
library(purrr)



# Define the file path
path <- "pp8_primhd_waittimes_20240829_JUN23MAY24 (deident).xlsx"

# Read each sheet into a dataframe with the corresponding name
DHBs_all_team_types <- read_excel(path, sheet = "table1")
NGOs_All_team_types <- read_excel(path, sheet = "table2")
DHB_MH_teams <- read_excel(path, sheet = "table3")
DHB_AOD_teams <- read_excel(path, sheet = "table4")
NGO_MH_teams <- read_excel(path, sheet = "table5")
NGO_AOD_teams <- read_excel(path, sheet = "table6")
Forensic_teams <- read_excel(path, sheet = "table7")
Exceptions <- read_excel(path, sheet = "table8")
No_contract_DHB <- read_excel(path, sheet = "table9")


```

# Creates a list of dataframes 

```{r}

dataframes <- list(
  DHBs_all_team_types,
  NGOs_All_team_types,
  DHB_MH_teams,
  DHB_AOD_teams,
  NGO_MH_teams,
  NGO_AOD_teams,
  Forensic_teams,
  Exceptions,
  No_contract_DHB
)

df_names <- c("DHBs_all_team_types", "NGOs_All_team_types", "DHB_MH_teams", 
              "DHB_AOD_teams", "NGO_MH_teams", "NGO_AOD_teams", 
              "Forensic_teams", "Exceptions", "No_contract_DHB")

```

# Simulating ethnicities, gender field (none given in deidentified data)

```{r}

ethnicities <- c("Maori", "Non-Maori, Non-Pacific", "Pasific", "Other")
ethnicitiesProbabilities <- c(0.4, 0.3, 0.2, 0.1) 
for (i in 1:length(dataframes)) {
  n <- nrow(dataframes[[i]])
  dataframes[[i]]$Ethnicity <- sample(ethnicities, size = n, replace = TRUE, prob = ethnicitiesProbabilities)
}

genders <- c("Male","Female","Other")
gendersProbabilities <- c(0.5,0.45,0.05)
for (i in 1:length(dataframes)) {
  n <- nrow(dataframes[[i]])
  dataframes[[i]]$Gender <- sample(genders, size = n, replace = TRUE, prob = gendersProbabilities)
}

```

# summarises wait days by table

```{r}

mean_wait_days <- sapply(dataframes, function(df){
  round(mean(df$WAIT_DAYS, na.rm= TRUE),2)
})

mean_summary <- data.frame(Table = df_names, Mean_WAIT_DAYS = mean_wait_days)

mean_summary



median_wait_days <- sapply(dataframes, function(df){
  median(df$WAIT_DAYS, na.rm= TRUE)
})

median_summary <- data.frame(Table = df_names, median_WAIT_DAYS = median_wait_days)

median_summary



```

```{r}


# Read the codeset
doc <- read_docx("HISO-10023.3-2024-PRIMHD-Code-Set-Standard.docx")



# Get the number of tables
num_tables <- docx_tbl_count(doc)

#save each table to a list entry
tables <- list()
for (i in 1:num_tables) {
  tables[[i]] <- docx_extract_tbl(doc, i)
}

# open a df 
all_code_descriptions <- data.frame(Code = character(), Description = character(), 
                        UsedForComment = character(), stringsAsFactors = FALSE)
#save each code description to a row
for (tbl in tables) {
  if (all(c("Code", "Description", "Used.for.Comment") %in% colnames(tbl))) {
    selected_tbl <- tbl %>% select(Code, Description, `Used.for.Comment`)
    all_code_descriptions <- rbind(all_code_descriptions, selected_tbl)
  }
}




```

# Function for mean, median per table

```{r}


mean_waits_per_organisation=list()

# calculates mean wait days per organisation for each dataframe
for (i in 1:length(dataframes)) {
  mean_table <- dataframes[[i]] %>%
    group_by(ORGANISATION_NAME) %>%  
    summarise(Mean_WAIT_DAYS = mean(WAIT_DAYS, na.rm = TRUE))  

  
  mean_waits_per_organisation[[df_names[i]]] <- mean_table
}


calculate_waits <- function(group, measure){
  result_list=list()
  for (i in 1:length(dataframes)) {
    mean_table <- dataframes[[i]] %>%
      group_by({{group}}) %>%  
      summarise(Mean_WAIT_DAYS = round(measure(WAIT_DAYS, na.rm = TRUE),2))  
  result_list[[df_names[i]]] <- mean_table
  }
  return(result_list)
}


```

```{r}

mean_waits_per_organisation <- calculate_waits(ORGANISATION_NAME, mean)
median_waits_per_organisation <-calculate_waits(ORGANISATION_NAME, median)

mean_waits_per_ageGroup <- calculate_waits(AGE_GROUP, mean)
median_waits_per_ageGroup <- calculate_waits(AGE_GROUP, median)


mean_waits_per_RefferalFrom <-calculate_waits(REFERRAL_FROM, mean)
median_waits_per_RefferalFrom <-calculate_waits(REFERRAL_FROM, median)

mean_waits_per_ethnicity <-calculate_waits(Ethnicity, mean)
median_waits_per_ethnicity <- calculate_waits(Ethnicity, median)

mean_waits_per_Gender <-calculate_waits(Gender, mean)
median_waits_per_Gender <- calculate_waits(Gender, median)




table(DHBs_all_team_types$REFERRAL_FROM)
```

```{r}


ggplot(mean_waits_per_organisation[[df_names[[3]]]], aes(x = reorder(ORGANISATION_NAME, Mean_WAIT_DAYS), y = Mean_WAIT_DAYS)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() + 
  labs(x = "Organisation Name", y = "Mean Wait Days", title = "Mean Wait Days by Organisation") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8))
```

```{r}

ggplot(mean_waits_per_organisation[[df_names[[1]]]], aes(x = reorder(ORGANISATION_NAME, Mean_WAIT_DAYS), y = Mean_WAIT_DAYS)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +  
  labs(x = "Organisation Name", y = "Mean Wait Days", title = "Mean Wait Days by Organisation") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8))

```




```{r}

combinedlist = bind_rows(dataframes, .id= "source_table")

is.null(combinedlist)

distinct_rows = combinedlist%>%
  select(-source_table)%>%
  distinct()

distinct_rows

```

```{r}
# - People with Referrals by TEAM_TYPE_CODE

People_with_Referrals_by_TEAM_TYPE_CODE <- distinct_rows %>%
  group_by(TEAM_TYPE_CODE) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by REFERRAL_FROM

People_with_Referrals_by_Referral_From <- distinct_rows %>%
  group_by(REFERRAL_FROM) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by FUNDING_DHB

People_with_Referrals_by_Funding_DHB <- distinct_rows %>%
  group_by(FUNDING_DHB) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by Age Group

People_with_Referrals_by_Age_Group <- distinct_rows %>%
  group_by(AGE_GROUP) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by Gender

People_with_Referrals_by_Gender <- distinct_rows %>%
  group_by(Gender) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by Ethnicity

People_with_Referrals_by_Ethnicity <- distinct_rows %>%
  group_by(Ethnicity) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID))

# - People with Referrals by INSCOPE_REFERRAL_END_CODE (replaced with endcode descriptions)

People_with_Referrals_by_Referral_End_Code <- distinct_rows %>%
  group_by(INSCOPE_REFERRAL_END_CODE) %>%
  summarize(Unique_Referral_ID_Count = n_distinct(REFERRAL_ID)) %>%
  left_join(all_code_descriptions, by = c("INSCOPE_REFERRAL_END_CODE" = "Code")) %>%
  select(Description, Unique_Referral_ID_Count)




```

